"""subtitle_quiz_attempt_and_fixes

Revision ID: 448fa79aded9
Revises: 27cbe46466a7
Create Date: 2026-06-23 19:07:22.929366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '448fa79aded9'
down_revision: Union[str, Sequence[str], None] = '27cbe46466a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quiz_attempts', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('quiz_attempts', sa.Column('company_id', sa.Integer(), nullable=False))
    op.add_column('quiz_attempts', sa.Column('score', sa.Float(), nullable=False))
    op.add_column('quiz_attempts', sa.Column('total_questions', sa.Integer(), nullable=False))
    op.add_column('quiz_attempts', sa.Column('correct_answers', sa.Integer(), nullable=False))
    op.add_column('quiz_attempts', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.create_foreign_key(None, 'quiz_attempts', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    op.drop_column('quiz_attempts', 'attempts')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quiz_attempts', sa.Column('attempts', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'quiz_attempts', type_='foreignkey')
    op.drop_column('quiz_attempts', 'updated_at')
    op.drop_column('quiz_attempts', 'correct_answers')
    op.drop_column('quiz_attempts', 'total_questions')
    op.drop_column('quiz_attempts', 'score')
    op.drop_column('quiz_attempts', 'company_id')
    op.drop_column('quiz_attempts', 'id')
    # ### end Alembic commands ###
