"""add_admin_role

Revision ID: 908db4ced154
Revises: be97cbd14eef
Create Date: 2026-06-14 16:37:46.484310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '908db4ced154'
down_revision: Union[str, Sequence[str], None] = 'be97cbd14eef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'company_members',
        sa.Column('is_admin', sa.Boolean(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('company_members')
    # ### end Alembic commands ###
