"""add_membership_and_changes_in_other_tables

Revision ID: be97cbd14eef
Revises: b0a329bceefe
Create Date: 2026-06-12 22:58:43.677216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be97cbd14eef'
down_revision: Union[str, Sequence[str], None] = 'b0a329bceefe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
